require 'rubygems'
require 'httparty'
require 'hashie'
require 'rash'

require 'factual/categories'
require 'factual/categories_response'
require 'factual/client'
require 'factual/core'
require 'factual/core_response'
require 'factual/crossref'
require 'factual/crosswalk'
require 'factual/places'
require 'factual/places_response'
require 'factual/resolve'
require "factual/version"